# Generated by Django 6.0.3 on 2026-03-23 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=100)),
                ("hospital", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("license_number", models.CharField(blank=True, max_length=50)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "diabetes_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Years with diabetes"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "predicted_class",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "No Diabetic Retinopathy"),
                            (1, "Mild DR"),
                            (2, "Moderate DR"),
                            (3, "Severe DR"),
                            (4, "Proliferative DR"),
                        ],
                        null=True,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "heatmap_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="heatmaps/%Y/%m/%d/"
                    ),
                ),
                ("class_probabilities", models.TextField(blank=True, null=True)),
                ("doctor_notes", models.TextField(blank=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="detection.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-analyzed_at"],
            },
        ),
    ]
